// wrapper file for entire app
import "../styles/globals.css";
import React from "react";
import AdminLayout from "@/components/adminLayout";
import DefaultLayout from "@/components/layout";
export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
  }

function App({ Component, pageProps, router }) {
    const isAdminPage = router.pathname === "/[...admin]";

    const Layout = isAdminPage ? AdminLayout : DefaultLayout
    console.log(router.pathname)
    return (
        <Layout>
            <Component {...pageProps} />     
        </Layout> 
    )
}

export default App