// wrapper file for entire app
import "../styles/globals.css";
import React from "react";
import Layout from "@/components/layout";

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
  }

function App({ Component, pageProps }) {
    return (
        <Layout>
            <Component {...pageProps} />     
        </Layout> 
    )
}

export default App